[project]
name = "bobcam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.21",
    "numpy<2.0",
    "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
    "pyttsx3>=2.98",
    "ffpyplayer>=4.3.2",
    "sounddevice>=0.4.7",
    "soundfile>=0.12.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.2.0",
    "pytest>=8.4.0",
]
